container:
  image: quay.io/prometheus/golang-builder:1.13-base

build_task:
  build_script: make

release_task:
  only_if: $CIRRUS_TAG =~ 'v.*'
  depends_on: build
  build_script: make build tarball
  tarball_artifacts:
    path: "ipmi_exporter-*.tar.gz"
    type: application/gzip
  matrix:
    - env:
        GOOS: linux
        GOARCH: amd64
    - env:
        GOOS: darwin
        GOARCH: amd64
    - env:
        GOOS: freebsd
        GOARCH: amd64
    - env:
        GOOS: linux
        GOARCH: arm64
