version: "2"
linters:
  enable:
    - misspell
    - revive
    - sloglint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
formatters:
  exclusions:
    generated: lax
